### ISSUE TITLE
Knockout Effect Doesn't Always Apply Bonus Damage

### ISSUE THREAD

**Issue by IProto** [thechungster/splinterlands-simulator#19]
**Original Game:** <https://splinterlands.com/?p=battle&id=sl_a1a2de7c1daf39d8f5dce5f54bea5a6b>
**Simulation:** <https://splintertools.io/battle?player=uwelang&battleId=sl_a1a2de7c1daf39d8f5dce5f54bea5a6b>
**Actual:** Loss
**Simulated:** ~93%+ Win

**Notes:** This is using the knockout ruleset and in the losing scenario Iza gets a stun on Acid Shooter. At the start of round 2 Acid Shooter has 5hp and gets hit from the Goblin Sorcerer for 3 then takes another 2 from the Screeching Vulture to kill it. Since the Acid Shooter is still stunned this should have been a hit for 6, killing the Acid Shooter and allowing the Screeching Vulture to attack another target.

**Comment by thechungster** [comment]
If anyone wants a crack at this one the bug is because the stun debuff is being cleared on the monster turn, instead of at the end of all monster turns.

This line should go outside of the while loop.
https://github.com/thechungster/splinterlands-simulator/blob/8f481288a273e523048296e3d8e403629f2760db/src/game.ts#L958

**Comment by IProto** [comment]
After looking at a few games I think the timing is supposed to be when it comes back to the monster's turn who applied the original stun. They unstun the monster they stunned, then get another opportunity to stun something.
