### ISSUE TITLE
Cleanse not removing all debuffs

### ISSUE THREAD

**Issue by IProto** [thechungster/splinterlands-simulator#66]
I'm not sure if this is an issue with the site, the log, or the simulator but I just noticed cleanse not really being respected in this battle: https://splintertools.io/battle?player=infinityx22&battleId=sl_cfc8cd584900de960495976fc9a13a8d.

![image](https://user-images.githubusercontent.com/48456132/178417130-2d4c2df5-affa-4c67-b840-5dbc8b999365.png)

This caused the simulation to think the conjurer would die much sooner since it wasn't getting healed anymore thanks to the affliction which shouldn't have still been there.

**Comment by YukiUmetsu** [comment]
Could this be caused by this part of the code?
https://github.com/thechungster/splinterlands-simulator/blob/d5a87b81c96ebf6e0779256317e5f0e8030a82bc/src/game_monster.ts#L185

indexOf
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf

```
      if (abilityUtils.UNCLEANSABLE_DEBUFFS.indexOf(key) > -1) {
        this.removeAllDebuff(key);
      }
```

indexOf(key) > -1  => the key exists in the array
It removes when debuff is in UNCLEANSABLE_DEBUFFS ?

**Comment by thechungster** [comment]
yeah that should be `=== -1`
we need to add some tests sometime
